const allproductsdetails =[
    {
      id:1,
      img:"images/pexels-photo-2912108.jpeg",
      offer:"20% off",
      title:" 2020 Limited Release Le Rosé ",
      category:"sparklingwine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },

    {
      id:2,
      img:"images/pexels-photo-2820146.jpeg",
      offer:"",
      title:" 2020 Limited Release Le Rosé ",
      category:"dessertwine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },
    {
      id:3,
      img:"images/pexels-photo-3934057.jpeg",
      offer:"20% off",
      title:" 2020 Limited Release Le Rosé ",
      category:"rosewine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },

    {
      id:4,
      img:"images/pexels-photo-2820146.jpeg",
      offer:"",
      title:" 2020 Limited Release Le Rosé ",
      category:"rosewine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },
    {
      id:5,
      img:"images/pexels-photo-2897305.jpeg",
      offer:"50% off",
      title:" 2020 Limited Release Le Rosé ",
      category:"rosewine",
      oldprice:"39.00",
      price:"29.00",
      link:"/shop",
    },

    {
      id:6,
      img:"images/pexels-photo-2820146.jpeg",
      offer:"40% off",
      title:" 2020 Limited Release Le Rosé ",
      category:"whitewine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },
    {
      id:7,
      img:"images/pexels-photo-2308939.jpeg",
      offer:"30% off",
      title:" 2020 Limited Release Le Rosé ",
      category:"whitewine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },
    {
      id:8,
      img:"images/pexels-photo-1479706.jpeg",
      offer:"",
      title:" 2020 Limited Release Le Rosé ",
      category:"whitewine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },
    {
      id:9,
      img:"images/pexels-photo-2912108.jpeg",
      offer:"20% off",
      title:" 2020 Limited Release Le Rosé ",
      category:"whitewine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },
    {
      id:10,
      img:"images/JP-wine-under-250-_255x255_cd3b2cb5-b368-408a-b28b-4ba802f9ee27.webp",
      offer:"",
      title:" 2020 Limited Release Le Rosé ",
      category:"redwine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },
    {
      id:11,
      img:"images/pexels-photo-3636002.jpeg",
      offer:"",
      title:" 2020 Limited Release Le Rosé ",
      category:"whitewine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },
    {
      id:12,
      img:"images/pexels-photo-3636002.jpeg",
      offer:"",
      title:" 2020 Limited Release Le Rosé ",
      category:"whitewine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },
    {
      id:13,
      img:"images/pexels-photo-3636002.jpeg",
      offer:"",
      title:" 2020 Limited Release Le Rosé ",
      category:"whitewine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },
    {
      id:14,
      img:"images/pexels-photo-3636002.jpeg",
      offer:"",
      title:" 2020 Limited Release Le Rosé ",
      category:"whitewine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },
    {
      id:15,
      img:"images/pexels-photo-3636002.jpeg",
      offer:"",
      title:" 2020 Limited Release Le Rosé ",
      category:"whitewine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },
    {
      id:16,
      img:"images/pexels-photo-3636002.jpeg",
      offer:"",
      title:" 2020 Limited Release Le Rosé ",
      category:"whitewine",
      oldprice:"39.00",
      price:"29.00",
      link:"/productsdetails",
    },
]

export default allproductsdetails;