const Bestsellproducts =[
      {
        id:1,
        img:"images/Densefit/ladiesglass1.png",
        offer:"New",
        title:"Ladies blue glass",
        cate:"Wears",
        // oldprice:"39.00",
        price:"18,500",
        link:"/shop",
      },

      {
        id:2,
        img:"images/Densefit/bluetoothconnectorhometheatresoundsystem43991.png", 
        offer:"Sales",
        title:"bluetooth home theatre",
        cate:"Electronics",
        // oldprice:"28.00",
        price:"43,990",
        link:"/shop",
      },
      {
        id:3,
        img:"images/Densefit/Defactor-women-regular-wear-9000.png",
        offer:"New",
        title:"Defactor women regular wear",
        cate:"Wears",
        // oldprice:"40.00",
        price:"9,000",
        link:"/shop",
      },

      {
        id:4,
        img:"images/Densefit/Dovemeninvisiblecream2090.png",
        offer:"15% off",
        title:"Dove men cream",
        cate:"Home care",
        // oldprice:"39.00",
        price:"4,090",
        link:"/shop",
      },
      {
        id:5,
        img:"images/Densefit/harpic950.png",
        offer:"10% off",
        title:"harpic toilet wash",
        cate:"Home care",
        // oldprice:"30.00",
        price:"1,050",
        link:"/shop",
      },

      {
        id:6,
        img:"images/Densefit/Nikeairzoomtypewear94000.png",
        offer:"Hot",
        title:"Nike air Zoom wear",
        cate:"Wears",
        // oldprice:"20.00",
        price:"94,000",
        link:"/shop",
      },
      {
        id:7,
        img:"images/Densefit/mens2in1short.png",
        offer:"30% off",
        title:"Unisex 2 in 1 short",
        cate:"Wears",
        // oldprice:"45.00",
        price:"16,800",
        link:"/shop",
      },
      {
        id:8,
        img:"images/product-7.png",
        offer:"20%",
        title:" 2020 Release Le Rosé ",
        cate:"Wine",
        // oldprice:"39.00",
        price:"105,000",
        link:"/shop",
      },
]

export default Bestsellproducts;